#!/bin/bash
#
# Edit command-line text. See #2453
# <https://github.com/qutebrowser/qutebrowser/issues/2453>.
# Adapted from @pkill-nine's userscript.

trap cleanup EXIT

cleanup() {
    rm "$qb_cmd"
}

qb_cmd=$(mktemp --tmpdir qutebrowser_XXXXXXXX)
cmd_prefix=$(echo "$QUTE_COMMANDLINE_TEXT" | head -c1)
echo "$QUTE_COMMANDLINE_TEXT" | cut -c 2- > "$qb_cmd"
st -e vim -n "$qb_cmd"

echo set-cmd-text "$cmd_prefix$(head -n1 "$qb_cmd")" >> "$QUTE_FIFO"
