#!/bin/bash
#
# Edit command-line text. See #2453
# <https://github.com/qutebrowser/qutebrowser/issues/2453>.

trap cleanup EXIT

cleanup() {
    rm "$qb_cmd"
}

qb_cmd=$(mktemp --tmpdir qutebrowser_XXXXXXXX)
echo "$QUTE_COMMANDLINE_TEXT" | cut -c 2- > "$qb_cmd"
urxvt -e vim -n "$qb_cmd"

echo set-cmd-text :$(head -n1 "$qb_cmd") >> "$QUTE_FIFO"
